# Generated by Django 4.2.7 on 2023-11-29 18:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Autorzy',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasztag', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Tagi',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=150)),
                ('zawartosc', models.CharField(max_length=200)),
                ('tresc', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('nazwa_obrazka', models.DateField(max_length=100)),
                ('data', models.DateField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posty', to='blog.autor')),
                ('hasztagi', models.ManyToManyField(null=True, to='blog.tag')),
            ],
            options={
                'verbose_name_plural': 'Posty',
            },
        ),
    ]
